server:
  port: 8083

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://capstone-db.cng4m02w2jrz.ap-southeast-2.rds.amazonaws.com:3306/capstone
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Vinni014291
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


